import Head from "next/head";
import Image from "next/image";
import Header from "../component/header/header";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import { Script } from "next/script";
import StatusListCard from "../component/generic/statusListCard";
import mainBg from "../public/assets/img/h1.jpg";
import { PageSectionA } from "../modules/pageSectionA";
import { PageSectionB } from "../modules/pageSectionB";



export default function Home() {
  const [profile, setprofile] = useState(false);
  const profileStatus = async () => {};

  //setTarget elment at higher z-index

  return (
    <>
      <div className={styles.MainHome} style={{}}>
        <Head>
          <title>blogs</title>
          <meta name="description" content="Generated by create next app" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.o"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
       <PageSectionA></PageSectionA>
       <PageSectionB ></PageSectionB>
        <br />
        {/* <homesection className={styles.main2}></homesection> */}
      </div>
    </>
  );
}
